#!/bin/bash

# Compiles all files in the src directory, checking for differences with files
# in the .temp directory to avoid redundant compilation, reducing compile times.
# Files are compiled and output to the out directory with the same name but no
# extension.

./create-dirs

# Gets all .cc files in the src directory.
files=`ls ./src | grep -o "^.*\.cc"`

# Compiles all found .cc files, with the same name but no extension.
for file in $files
do
  # If a temp file doesn't exist or one exists but is different from the source
  # file, compile the source file and create a new temp copy.
  if [ ! -f ./.temp/$file ] || ! cmp -s ./src/$file ./.temp/$file
  then
    file_name=`echo $file | grep -o "^.*\."`
    
    length=${#file_name}
    length=$length-1
    file_name=${file_name:0:$length}
    
    clang++ -std=c++11 ./src/$file -o ./out/$file_name -g

    cp ./src/$file ./.temp/
  fi
done

./clean-dirs